### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by corbob** [test-kitchen/kitchen-pester#90]
Are there any plans or timeline for a new release of `kitchen-pester`? I would like to be able to use some of the new features in my tests, but it depends on them being released so I can consume them in the CI/CD pipeline.

Is there anything holding up a release that I could potentially assist with?

/cc: @tas50 @floh96

**Comment by floh96** [comment]
Im not a maintainer of this repository and tas50 left Chef. I belive you are pinging the wrong people here.

**Comment by vexx32** [comment]
Hi @floh96!

In that case, who should @corbob be pinging? Until recently I was both a maintainer of the repository and the kitchen-pester gem, and could have addressed this request.

I have since been removed as owner/maintainer of the gem along with _most_ of the owners other than @tas50 and one other person I have no contact for with no communication, so I'm unsure who is supposed to be owning/maintaining the gem.

Do you know if there is someone at Chef who is tasked with maintaining this currently?

**Comment by floh96** [comment]
Hi @vexx32 

First of all I'm not affiliated with chef or this repo. I have only contributed a very small ci fix.
@damacus and @Xorima are listed as owners of the gem along with tas50 maybe they can help?

**Comment by gep13** [comment]
@damacus just wanted to follow up with this question...

Is this something that you can help with, or who is the best person to talk to about this?

Thanks

**Comment by Xorima** [comment]
Sorry it took so long, I think I have released this correctly as v1.2.0? (I haven't done a gem release in a while) 

Shout if you need any more help!

**Comment by vexx32** [comment]
Thank you! 💖

**Comment by corbob** [comment]
Thank you for getting that done @Xorima.

Apologies and thanks to @floh96 for the clarifications and assistance identifying who might be able to do a release. I realize when I first looked at the recent commits I missed that yours were part of a pr and not part of having commit access. 

💖
